# Julia dependencies for Kurucz-Korg integration
#
# To install, from Julia REPL:
#   ] activate examples/kurucz_integration
#   ] instantiate

name = "KuruczKorgIntegration"
uuid = "12345678-1234-1234-1234-123456789012"
version = "1.0.0"

[deps]
Korg = "c175f4bb-d0c2-41fb-a37c-c1c0edf99c47"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.6"
Korg = "0.24"
PyCall = "1.92"
HDF5 = "0.16, 0.17"
ProgressMeter = "1.7"
Plots = "1.29"
